configurationOverrides:
  "offsets.topic.replication.factor": 3
  "log.retention.hours": 4
  "log.message.timestamp.type": "LogAppendTime"

replicas: 3

persistence:
  enabled: false

zookeeper:
  replicaCount: 3
  persistence:
    enabled: false

