apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rbd
  annotations:
     storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: rbd-provisioner
  fsType: ext4
  imageFeatures: layering
  imageFormat: "2"
  monitors: 10.242.11.1:6789,10.242.11.2:6789,10.242.11.3:6789
  pool: kube
  userId: admin
  userSecretName: ceph-secret-admin
  userSecretNamespace: rbd-provisioner
provisioner: ceph.com/rbd
reclaimPolicy: Delete
volumeBindingMode: Immediate
