private_kafka_cluster: false
private_etcd_cluster: false

defaults:
  log_level: "DEBUG"
  image_pullPolicy: "Always"

services:
  kafka:
    adapter:
      service: cord-kafka.default.svc.cluster.local
      port: 9092
    cluster:
      service: cord-kafka.default.svc.cluster.local
      port: 9092

  etcd:
    service: voltha-etcd-cluster-client.default.svc.cluster.local
    port: 2379
